import SwiftUI

struct CartView: View {
    var body: some View {
        ZStack() {
            Group {
                Rectangle()
                    .foregroundColor(.clear)
                    .frame(width: 834, height: 1194)
                    .background(Color(red: 0.09, green: 0.09, blue: 0.09))
                    .offset(x: 0, y: 0)
                ZStack() {
                    ZStack() { }
                    .frame(width: 121.18, height: 29.97)
                    .offset(x: -0, y: -15.02)
                    ZStack() { }
                    .frame(height: 28.31)
                    .offset(x: -0, y: 15.85)
                }
                .frame(width: 122, height: 60)
                .offset(x: 443, y: -31)
                .rotationEffect(.degrees(-90))
                Text("Independent Trading Co. ")
                    .font(Font.custom("Lexend", size: 10).weight(.light))
                    .tracking(0.10)
                    .lineSpacing(29)
                    .foregroundColor(.white)
                    .offset(x: 254.50, y: -384.50)
                    .rotationEffect(.degrees(-90))
                Text("Hersey Hoodie with Husky Head  ")
                    .font(Font.custom("Lexend", size: 15))
                    .tracking(0.15)
                    .lineSpacing(15)
                    .foregroundColor(.white)
                    .offset(x: 293.50, y: -331.50)
                    .rotationEffect(.degrees(-90))
                Text("Size S")
                    .font(Font.custom("Lexend", size: 10))
                    .tracking(0.10)
                    .lineSpacing(15)
                    .foregroundColor(.white)
                    .offset(x: 134.50, y: -359.50)
                    .rotationEffect(.degrees(-90))
                Text("Gray")
                    .font(Font.custom("Lexend", size: 10))
                    .tracking(0.10)
                    .lineSpacing(15)
                    .foregroundColor(.white)
                    .offset(x: 146.50, y: -359.50)
                    .rotationEffect(.degrees(-90))
                Text("$45")
                    .font(Font.custom("Lexend", size: 10))
                    .tracking(0.10)
                    .lineSpacing(15)
                    .foregroundColor(.white)
                    .offset(x: 190.50, y: -359.50)
                    .rotationEffect(.degrees(-90))
                Text("Independent Trading Co. ")
                    .font(Font.custom("Lexend", size: 10).weight(.light))
                    .tracking(0.10)
                    .lineSpacing(29)
                    .foregroundColor(.white)
                    .offset(x: 68.50, y: -384.50)
                    .rotationEffect(.degrees(-90))
                Text("Hersey Hoodie with Husky Head  ")
                    .font(Font.custom("Lexend", size: 15))
                    .tracking(0.15)
                    .lineSpacing(15)
                    .foregroundColor(.white)
                    .offset(x: 39.50, y: -359.50)
                    .rotationEffect(.degrees(-90))
                Text("Size S")
                    .font(Font.custom("Lexend", size: 10))
                    .tracking(0.10)
                    .lineSpacing(15)
                    .foregroundColor(.white)
                    .offset(x: -51.50, y: -359.50)
                    .rotationEffect(.degrees(-90))
            };Group {
                Text("Gray")
                    .font(Font.custom("Lexend", size: 10))
                    .tracking(0.10)
                    .lineSpacing(15)
                    .foregroundColor(.white)
                    .offset(x: -39.50, y: -359.50)
                    .rotationEffect(.degrees(-90))
                Text("$45")
                    .font(Font.custom("Lexend", size: 10))
                    .tracking(0.10)
                    .lineSpacing(15)
                    .foregroundColor(.white)
                    .offset(x: 4.50, y: -359.50)
                    .rotationEffect(.degrees(-90))
                Text("My Cart")
                    .font(Font.custom("Lexend", size: 24))
                    .tracking(0.24)
                    .lineSpacing(30)
                    .foregroundColor(.white)
                    .offset(x: 460.50, y: -501)
                    .rotationEffect(.degrees(-90))
                Rectangle()
                    .foregroundColor(.clear)
                    .frame(width: 137, height: 137)
                    .background(
                        AsyncImage(url: URL(string: "https://via.placeholder.com/137x137"))
                    )
                    .offset(x: 229.50, y: -447.50)
                    .rotationEffect(.degrees(-90))
                Rectangle()
                    .foregroundColor(.clear)
                    .frame(width: 137, height: 137)
                    .background(
                        AsyncImage(url: URL(string: "https://via.placeholder.com/137x137"))
                    )
                    .offset(x: 43.50, y: -447.50)
                    .rotationEffect(.degrees(-90))
                Rectangle()
                    .foregroundColor(.clear)
                    .frame(width: 578, height: 0)
                    .overlay(
                        Rectangle()
                            .stroke(Color(red: 0.49, green: 0.49, blue: 0.49), lineWidth: 0.50)
                    )
                    .offset(x: 474, y: -517)
                    .rotationEffect(.degrees(-89.90))
                Rectangle()
                    .foregroundColor(.clear)
                    .frame(width: 578, height: 0)
                    .overlay(
                        Rectangle()
                            .stroke(Color(red: 0.49, green: 0.49, blue: 0.49), lineWidth: 0.50)
                    )
                    .offset(x: 288, y: -517)
                    .rotationEffect(.degrees(-89.90))
                Rectangle()
                    .foregroundColor(.clear)
                    .frame(width: 578, height: 0)
                    .overlay(
                        Rectangle()
                            .stroke(Color(red: 0.49, green: 0.49, blue: 0.49), lineWidth: 0.50)
                    )
                    .offset(x: 102, y: -517)
                    .rotationEffect(.degrees(-89.90))
                Rectangle()
                    .foregroundColor(.clear)
                    .frame(width: 85, height: 32)
                    .background(Color(red: 0.85, green: 0.85, blue: 0.85))
                    .offset(x: 199.50, y: -8)
                    .rotationEffect(.degrees(-90))
                Rectangle()
                    .foregroundColor(.clear)
                    .frame(width: 88, height: 32)
                    .background(Color(red: 0.85, green: 0.85, blue: 0.85))
                    .offset(x: 15, y: -12)
                    .rotationEffect(.degrees(-90))
            };Group {
                Text("-")
                    .font(Font.custom("Lexend", size: 24))
                    .tracking(0.24)
                    .lineSpacing(30)
                    .foregroundColor(Color(red: 0.49, green: 0.49, blue: 0.49))
                    .offset(x: 162.50, y: -2.50)
                    .rotationEffect(.degrees(-90))
                Text("+")
                    .font(Font.custom("Lexend", size: 24))
                    .tracking(0.24)
                    .lineSpacing(30)
                    .foregroundColor(Color(red: 0.49, green: 0.49, blue: 0.49))
                    .offset(x: 162.50, y: 57.50)
                    .rotationEffect(.degrees(-90))
                Text("1")
                    .font(Font.custom("Lexend", size: 15))
                    .tracking(0.15)
                    .lineSpacing(30)
                    .foregroundColor(Color(red: 0.49, green: 0.49, blue: 0.49))
                    .offset(x: 159.50, y: 29.50)
                    .rotationEffect(.degrees(-90))
                Text("-")
                    .font(Font.custom("Lexend", size: 24))
                    .tracking(0.24)
                    .lineSpacing(30)
                    .foregroundColor(Color(red: 0.49, green: 0.49, blue: 0.49))
                    .offset(x: -23.50, y: -6.50)
                    .rotationEffect(.degrees(-90))
                Text("+")
                    .font(Font.custom("Lexend", size: 24))
                    .tracking(0.24)
                    .lineSpacing(30)
                    .foregroundColor(Color(red: 0.49, green: 0.49, blue: 0.49))
                    .offset(x: -23.50, y: 53.50)
                    .rotationEffect(.degrees(-90))
                Text("1")
                    .font(Font.custom("Lexend", size: 15))
                    .tracking(0.15)
                    .lineSpacing(30)
                    .foregroundColor(Color(red: 0.49, green: 0.49, blue: 0.49))
                    .offset(x: -26.50, y: 25.50)
                    .rotationEffect(.degrees(-90))
                Text("Order Summary")
                    .font(Font.custom("Lexend", size: 24))
                    .tracking(0.24)
                    .lineSpacing(30)
                    .foregroundColor(.white)
                    .offset(x: 235, y: 165.50)
                    .rotationEffect(.degrees(-90))
                Text("Total")
                    .font(Font.custom("Lexend", size: 24))
                    .tracking(0.24)
                    .lineSpacing(30)
                    .foregroundColor(.white)
                    .offset(x: 75, y: 165.50)
                    .rotationEffect(.degrees(-90))
                Text("$98.00")
                    .font(Font.custom("Lexend", size: 24))
                    .tracking(0.24)
                    .lineSpacing(30)
                    .foregroundColor(.white)
                    .offset(x: 20, y: 434.50)
                    .rotationEffect(.degrees(-90))
            };Group {
                Text("Clothing cost (2)")
                    .font(Font.custom("Lexend", size: 15))
                    .tracking(0.15)
                    .lineSpacing(30)
                    .foregroundColor(.white)
                    .offset(x: 169, y: 165.50)
                    .rotationEffect(.degrees(-90))
                Text("$90")
                    .font(Font.custom("Lexend", size: 15))
                    .tracking(0.15)
                    .lineSpacing(30)
                    .foregroundColor(.white)
                    .offset(x: 94, y: 484.50)
                    .rotationEffect(.degrees(-90))
                Text("$8")
                    .font(Font.custom("Lexend", size: 15))
                    .tracking(0.15)
                    .lineSpacing(30)
                    .foregroundColor(.white)
                    .offset(x: 63, y: 493.50)
                    .rotationEffect(.degrees(-90))
                Text("Maintenance fee")
                    .font(Font.custom("Lexend", size: 15))
                    .tracking(0.15)
                    .lineSpacing(30)
                    .foregroundColor(.white)
                    .offset(x: 137, y: 165)
                    .rotationEffect(.degrees(-90))
                Rectangle()
                    .foregroundColor(.clear)
                    .frame(width: 333, height: 0)
                    .overlay(Rectangle()
                    .stroke(.white, lineWidth: 0.50))
                    .offset(x: 160.50, y: 155)
                    .rotationEffect(.degrees(-90))
                Rectangle()
                    .foregroundColor(.clear)
                    .frame(width: 348, height: 43.38)
                    .background(Color(red: 1, green: 0.40, blue: 0.11))
                    .offset(x: 84.36, y: 172.69)
                    .rotationEffect(.degrees(-90))
                Text("Pick up")
                    .font(Font.custom("Lexend", size: 24))
                    .tracking(0.24)
                    .lineSpacing(30)
                    .foregroundColor(.white)
                    .offset(x: -53, y: 295.50)
                    .rotationEffect(.degrees(-90))
                Text("<")
                    .font(Font.custom("Lexend", size: 48))
                    .tracking(0.48)
                    .lineSpacing(30)
                    .foregroundColor(.white)
                    .offset(x: 378, y: -502)
                    .rotationEffect(.degrees(-90))
            }
        }
        .frame(width: 834, height: 1194)
        .background(.white)
        .rotationEffect(.degrees(90))
    }
}


struct CartView_Previews: PreviewProvider {
    static var previews: some View {
        CartView()
         
    }
}
